export const sizeOptions = [
	{label: 'S', value: 'S'},
	{label: 'M', value: 'M'},
	{label: 'L', value: 'L'},
	{label: 'XL', value: 'XL'},
	{label: 'XXL', value: 'XXL'},
];
export const colorOptions = [
	{label: 'Black', value: 'Black'},
	{label: 'White', value: 'White'},
	{label: 'Red', value: 'Red'},
	{label: 'Blue', value: 'Blue'},
	{label: 'Green', value: 'Green'},
	{label: 'Yellow', value: 'Yellow'},
	{label: 'Pink', value: 'Pink'},
	{label: 'Purple', value: 'Purple'},
	{label: 'Orange', value: 'Orange'},
	{label: 'Brown', value: 'Brown'},
	{label: 'Grey', value: 'Grey'},
	{label: 'Navy Blue', value: 'Navy Blue'},
	{label: 'Sky Blue', value: 'Sky Blue'},
	{label: 'Maroon', value: 'Maroon'},
	{label: 'Beige', value: 'Beige'},
	{label: 'Cream', value: 'Cream'},
	{label: 'Turquoise', value: 'Turquoise'},
	{label: 'Mint', value: 'Mint'},
	{label: 'Teal', value: 'Teal'},
	{label: 'Olive', value: 'Olive'},
	{label: 'Khaki', value: 'Khaki'},
	{label: 'Burgundy', value: 'Burgundy'},
	{label: 'Peach', value: 'Peach'},
	{label: 'Lavender', value: 'Lavender'},
	{label: 'Magenta', value: 'Magenta'},
	{label: 'Silver', value: 'Silver'},
	{label: 'Gold', value: 'Gold'},
	{label: 'Rose Gold', value: 'Rose Gold'},
	{label: 'Charcoal', value: 'Charcoal'},
	{label: 'Cyan', value: 'Cyan'},
	{label: 'Royal Blue', value: 'Royal Blue'},
	{label: 'Off White', value: 'Off White'},
	{label: 'Ivory', value: 'Ivory'},
	{label: 'Sand', value: 'Sand'},
	{label: 'Mustard', value: 'Mustard'},
	{label: 'Wine', value: 'Wine'},
	{label: 'Forest Green', value: 'Forest Green'},
	{label: 'Lime', value: 'Lime'},
	{label: 'Tan', value: 'Tan'},
	{label: 'Coral', value: 'Coral'},
	{label: 'Fuchsia', value: 'Fuchsia'},
	{label: 'Indigo', value: 'Indigo'},
	{label: 'Violet', value: 'Violet'},
	{label: 'Chocolate', value: 'Chocolate'},
	{label: 'Mint Green', value: 'Mint Green'},
	{label: 'Ash', value: 'Ash'},
	{label: 'Slate Grey', value: 'Slate Grey'},
];
